plugins:
- jekyll-loading-lazy
- jekyll-relative-links

relative_links:
  enabled: true
  collections: true

theme: minima

title: Film Packaging Archive
description: High-resolution scans of photographic film packaging

